[package]
name = "lamp-server"
version = "1.0.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1.32", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "3.5", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1", features = ["axum"] }