[package]
name = "lamp-server"
version = "1.0.0"
edition = "2021"

[dependencies]
hsv = "0.1"
axum = "0.6"
sha256 = "1.4"
serde_json = "1.0"
tokio = { version = "1.32", features = ["full"] }
#serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
utoipa = { version = "3.5", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1", features = ["axum"] }