[package]
name = "lamp-server"
version = "1.0.0"
edition = "2021"

[dependencies]
hsv = "0.1"
axum = "0.6"
sha256 = "1.4"
serde_json = "1.0"
#serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.34", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
utoipa = { version = "4.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "4.0", features = ["axum"] }