[package]
name = "lamp-server"
version = "1.0.0"
edition = "2021"

[dependencies]
hsv = "0.1" # hsv to rgb
sha256 = "1.4" # calculate sha256 hash
itertools = "0.12" # better iterator handling
axum = { version = "0.6", features = ["headers"] } # webserver
tokio = { version = "1.34", features = ["full"] } # async runtime
reqwest = { version = "0.11", features = ["json"] } # make http requests
# get current time with timezone
chrono    = "0.4"
chrono-tz = "0.8"
# (de)serialize to/from json
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# swagger ui / openapi documentation support for axum
utoipa = { version = "4.1", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "4.0", features = ["axum"] }